### ISSUE TITLE
Chained selectors

### ISSUE THREAD

**Issue by abb1991** [ElinaIvanova/f1-3-c2p1-colmar-academy#4]
Your CSS also shows a lot of good decisions. I like your use of multiple selectors to DRY up your code.

```
.thesis .main-info .figure iframe,
.thesis .main-info .figure object,
.thesis .main-info .figure embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  object-fit: contain;
}
```

In the above example to do you think your work would benefit from a class that applied to all of those elements? Why/why not?

**Comment by ElinaIvanova** [comment]
That's a thing, thank you. I haven't thought of it but that would definitely be useful in this case (as well as many others).
